# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b7ff184f949dd3cac5b2ac2e85f23ffa2f0803509b4349199d5bf8134fff8539504b3515b1d33153d1107345d20456b820952a92aa3048fce092e8977c9f091c

test:
  secret_key_base: 8dcebd321ba3129c4a88af9fae4914821e346dea98eb6c95dabb0876257461d800514d552d62dde0b02f6d185fff1ca01bf7e52de069a61179be73e234668f27

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
